#######################
#=MESSAGE=OVER=HEADER=#
#######################

version: 1.3 #DONT TOUCH!

settings: #plugin settings
  listener: #General listener. If it is disabled, holograms can only be called by a command.
    chat: true
  message:
    clearColorFromPlayerMessage: false
  command:
    moh-send:
      enable: true
      bubbleConfig: "messages"
  generalChat: #The hologram appears if the player wrote a message in the general chat
      enable: true
      bubbleConfig: "messages" #The configuration for this message. In this case, the "messages" configuration applies
  privateChat: # /tell or /msg command
      enable: true
      bubbleConfig: "privateMessages"

testConfigBubble1: #Some message configuration
  isBubble: true
  particle:
    enable: false
  sound:
    enable: false
  settings:
    format: '&7%message%'

privateMessages:
  isBubble: true
  settings:
    format: '&7%message%'
    #There are no other fields specified in this config, so the other fields have a default value.

messages: #default
  isBubble: true #don't touch. It magic
  particle:
    enable: true
    particleType: CLOUD # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    count: 4 #count of particle
    offsetX: 0.2 #the maximum random offset on the X axis
    offsetY: 0.2 #the maximum random offset on the X axis
    offsetZ: 0.2 #the maximum random offset on the Z axis
  sound:
    enable: true
    soundType: BLOCK_ANVIL_STEP # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    volume: 3 #The volume of the sound
    pitch: 3 #The pitch of the sound
  settings:
    format: '%player_name% %message%' #Default format! Supports PlaceholderAPI and HEX colors (example: &#123456)
    #format: #Group format!
     #'0': #priority
        #format: '%message%' #default format. format haven't permission
     #'1':
        #perm: 'perm.vip' #perm.vip
        #format: '&cVIP &e%message%' #format of perm.vip
    distance: 10
    biasY: 2.15 #height spawn of Bubble Message. The value is calculated experimentally.
    visibleTextForOwner: true
    delay: 4 #in seconds. Bubble life time
    sizeLine: 24 #Maximum size of one bubble
    clearColorFromPlayerMessage: true
